services:
  - type: pserv
    name: agendamento-db
    env: postgresql
    plan: free

  - type: web
    name: agendamento-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install; npx prisma generate; npm run build
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: agendamento-db
          property: connectionString

  - type: web
    name: agendamento-frontend
    runtime: static
    rootDir: frontend
    plan: free
    buildCommand: npm install; npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://agendamento-backend.onrender.com
